version: '3.9'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - /home/misaelmoreira/dados/volumes/postgres:/var/lib/postgresql/data